version: "3"
services:
  frontend:
    build: 
      context: url-shortener-react/
      args:
        VITE_BACKEND_URL: http://localhost:8080
        VITE_REACT_FRONT_END_URL: http://localhost
    ports:
      - "80:80"
  backend:
    build:
      context: url-shortener-sb/
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/urlshortenerdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - FRONTEND_URL=http://localhost
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=urlshortenerdb
    - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
      
    